package com.github.svetanis.base.serializer.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Data Transfer Object representing a single choice generated by the model.
 * In a non-streaming response, this contains a full message. In a streaming response, it contains a delta.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record OpenAiChoice(
    @JsonProperty("message") OpenAiMessage message,
    @JsonProperty("delta") OpenAiMessage delta,
    @JsonProperty("finish_reason") String finishReason,
    @JsonProperty("index") Integer index
) {}
